### ISSUE TITLE
Delay required after initializing MachineMotion object

### ISSUE THREAD

**Issue by mohitpatel-vention** [VentionCo/mm-python-api#27]
When instantiating the MachineMotion object, I noticed an issue while using certain methods. It seems like there needs to be some delay added to properly initialize the object.

For example if I were to check if the IO expander is available (if connected to the controller) using isIoExpanderAvailable() without a delay, it will output false. If I add a 1 second delay (time.sleep(1)) in between and call the method again it will return true as expected:

code: 
![image](https://user-images.githubusercontent.com/55992755/71210895-00077800-227c-11ea-8162-bc71c50263a2.png)

output:
![image](https://user-images.githubusercontent.com/55992755/71210926-0c8bd080-227c-11ea-9a44-b469cadc464f.png)

I presume that it takes some time for for the object to initialize. We should add a delay right after the instantiation of the MachineMotion object.

**Comment by jack-dundas** [comment]
Hey Mohit!
 Your hunch is pretty much right - but instead of waiting an arbitrary amount you should be able to wait for MachineMotion.isReady() to return True. 
Or something along those lines - there's an isReady functionality that waits until the machineMotion ports are ready for action. 

the function isIoExpanderAvailable returns the value of a machineMotion class variable that gets updated once a "IOExpander available" topic is published to. 
The class level variable is initialized to false and then turns true once the "IO available" message is published. It might be better to initialize the class parameter to 'Null' instead of false so a more descriptive error can be thrown.

Let's chat when you're back in!

**Comment by jack-dundas** [comment]
Let's add a 'wait for socket topic' in the 'io expander available' function in the library. This should prevent your error from happening.
![image](https://user-images.githubusercontent.com/56700688/71686562-7ec6df80-2d69-11ea-9296-3acf8dfa8539.png)

**Comment by guirb-vention** [comment]
Issue was replicated using other MQTT topic, I'm moving the discussion to issue #28
